### ISSUE TITLE
Nazar noise help

### ISSUE THREAD

**Issue by tcrowe** [tcrowe/noise-wasm-wrapper#1]
@nazar-pc Originally I was trying to get it to automatically upgrade a `stream.Duplex` but I settled on this API for now. If you see easy ways I can improve it or get the 'To-do' items working please let me know. And thank you. 🤓👍

**Comment by nazar-pc** [comment]
Don't really have time to dig deeper, I was mostly using noise-c.wasm with WebRTC, which has its own set of challenges.
noise-c.wasm is intentionally low-level, such that you can build whatever you need on top of any protocol using it.

**Comment by tcrowe** [comment]
Not a problem. I'll eventually improve it so the other patterns work. For now it's just using 'XK' and some defaults. That works fine. Take care! 👋
